### ISSUE TITLE
AccessViolationException when trying to cherry pick messages on ParameterNumber

### ISSUE THREAD

**Issue by rikkert-jan** [0x1mason/GribApi.NET#69]
Hi there!

I'm trying to read a GRIB file with your api, in order to find the total precipitation forecast.
I can not search on the name of a parameter due to some issues with the format of our GRIB files, so I have to search by ParameterNumber.

When using your example code for cherry picking by parameter name/description nothing goes wrong
```
            using (GribFile file = new GribFile(@"<path to our file>"))
            {
                var vComp = file.Where(m => m.Name.Contains("V-component of wind m s**-1")).First();

                foreach (var val in vComp.GeoSpatialValues)
                {
                    Console.WriteLine("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value);
                }
            }
```

But when trying to change `file.Where(m => m.Name.Contains("V-component of wind m s**-1").First();` to `file.Where(m => m.ParameterNumber == 061).First()` I get an AccessViolationException. This exception also pops up in the QuickWatch of visual studio while debugging.

Am I missing something here?

I'm using the files from this page [https://data.knmi.nl/datasets/harmonie_p1/0.2?q=HARMONIE,%20nabij%20oppervlakte%20parameters](url)

It is in dutch... But the specific model is called HARMONIE, and it is a file format based on GRIB 1 (but with a few quirks which I don't understand)

Thanks in advance!

**Comment by IdahoSixString** [comment]
@rikkert-jan Try this.

            using (GribFile file = new GribFile(@"<path to our file>"))
            {
                var vComp = file.Where(m => m.Name.Contains("V-component of wind m s**-1")).First();

                foreach (var val in vComp.GeoSpatialValues)
                {
                    if (val.IsMissing) { continue; }
                    Console.WriteLine("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value);
                }
            }

**Comment by 0x1mason** [comment]
Can you try the 1.0.0 beta? It resolved a number of these problems.

**Comment by rikkert-jan** [comment]
Thanks for the suggestion! I've tried it out, but unfortunately it does not seem to solve the problem. It still throws the same exception.

**Comment by jnyrup** [comment]
Does the QuickWatch provide a stack trace or anything else?
In #61 I also had an `AccessViolationException`. This was due to an invalid grib2 that made the jpeg-decoder throw an exception whose error text was apparently not marshalled properly from c++ to c# in release mode. So C# tried to access already unallocated memory and hence the `AccessViolationException`.

Have you tried parsing the grib2 files with another parser?
Try http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/

**Comment by 0x1mason** [comment]
I've released 1.0.0-beta2. I'm hoping these issues are resolved there. Lmk if you find otherwise.

**Comment by rikkert-jan** [comment]
Thanks for your answer! I've tried to implement the 1.0.0-beta2, but I can't get it to work... when I run it, an exception is thrown with an innerexception saying I need to define a correct path to the Grib.API. I've tried shadowcopying, but then I get an exception that it can't find boot.def... I haven't got this issue with previous versions. Any thoughts on how I can get it to work?

Thanks in advance!

**Comment by 0x1mason** [comment]
@rikkert-jan Try the following before doing anything else:
```
		static void MyFunc ()
		{
			GribEnvironment.Init();
			GribEnvironment.DefinitionsPath = @"C:\<path\to\myproject>\packages\Grib.Api.1.0.0-beta2\Grib.Api\definitions";
                        // ...
		}

**Comment by rikkert-jan** [comment]
Thanks! It works now, however the same problem persists... I get an AccessViolation exception when I quickwatch or search on the ParameterNumber...

**Comment by 0x1mason** [comment]
@rikkert-jan I can't reproduce the AccessViolation, however I did get a GribApiException because that key was not found. I can fix that. In the meantime, use `msg["paramId"].AsInt()` or `.AsString()`. It can be really helpful to dump all the keys for your message to confirm what's there. That way you can get unblocked when you hit one of my mistakes ;).

Regarding the AccessViolation. Try completely uninstalling GribApi. Delete the GribApi directory with all the files in it. Then try reinstalling.

**Comment by 0x1mason** [comment]
Fixed

**Comment by rikkert-jan** [comment]
Thank you very much! It now shows the parameter numbers. There's still one problem... Some parameternumbers seem a bit off. 

I want to know the values of a parameter abreviated as CR, aka Cumulatieve Som Regen, Dutch for Total Precipitation. I've been told by the distributor of the GRIB sets that this wrapper (and if I remember correctly the original GribAPI itself too) is not fully compatible with their files and that names and parameters may seem mixed up. As a result of this I've been told to browse by parameter number and the level. The parameter I need is number 61, and the level is 457. I can't seem to find any of this numbers in the GRIB message. I also get parameter numbers higher than 20000. This does not seem right. 

I don't know if the problem is in the wrapper, the GribApi or in the files... But that doesn't matter that much. I'm more curious if you might have an explanation.

Thanks in advance!

**Comment by 0x1mason** [comment]
@rikkert-Jan I'll take a look at it. I'm optimistic that we can at least find a workaround.

What degribber does your provider recommend?

**Comment by rikkert-jan** [comment]
That sounds great, thank you for your quick reply and your optimism :D! My provider recommended ecCodes from ECMWF. Unfortunately I can not get it to work on my PC.

**Comment by 0x1mason** [comment]
Ha! I switched to eccodes for the next release, so we should be good.

**Comment by 0x1mason** [comment]
@rikkert-jan Try the beta 4. It uses eccodes.

**Comment by LeonBatta** [comment]
Hi. Unfortunately my collegue rikkert-jan left our company. I worked with him on this issue, so now I took over the testing of it.
I installed the beta 4, but still most items have parameterNumber 0 and parameterName "unknown". When items do have a parameterNumber, often this number does not match with the ones our weather provider gave us.
The weather provider uses this command to get a list of keys:
grib_ls -p indicatorOfParameter,indicatorOfTypeOfLevel,level [filename]
With beta 4 we do get the correct Level, but not the correct ParameterNumber (I assume this contains the indicatorofParameter).
Any ideas for a solution would be appreciated.

**Comment by 0x1mason** [comment]
You should be able to do `var indicator = gribMessage["indicatorOfParameter"].AsString ();`

You can do the same for any other you'd provide to grib_ls. Try dumping the keys as in the README to see if you can find what you're looking for. If You find it and think I can improve the documentation, please lmk.

**Comment by 0x1mason** [comment]
Here's an example dump: https://github.com/0x1mason/GribApi.NET/blob/master/docs/TypicalKeyDump.md. You should also be able to call `message.Dump ()` to get a pretty printed string

**Comment by LeonBatta** [comment]
It works! I can now filter on "indicatorOfParameter" and "level". Great. Thank you for the support.
When will this version be released?

**Comment by 0x1mason** [comment]
Should be soon--by the end of September if not sooner.

**Comment by 0x1mason** [comment]
Glad it works for you.
